#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    echo "Push to main is blocked. Work through dev or feature branches." >&2
    exit 1
  fi
done

exit 0
