"""팀 카테고리(시나리오) → 영수님 family 페르소나 매핑 생성.

카테고리와 family는 모듈(8종)이 동일하고 이름이 대응된다. 같은 모듈 안에서 이름 임베딩
유사도로 top-1 family를 고른다. 결과를 사람 검수용 YAML(data/npcs/category_family_map.yaml)로.

사용: docker compose exec api python -m app.scripts.map_category_family [out_path]
"""

import asyncio
import logging
import math
import sys
from pathlib import Path

from sqlalchemy import select

from app.content.persona_parser import load_families
from app.core.config import settings
from app.llm import get_llm
from app.models import TeamCategory

logger = logging.getLogger(__name__)

AUTO_GEN_MARKER = "# AUTO-GENERATED by map_category_family"


def _cosine(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b, strict=True))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    return dot / (na * nb) if na and nb else 0.0


async def build_mapping() -> list[dict]:
    from app.core.db import SessionFactory

    families = load_families()
    fam_list = list(families.values())
    async with SessionFactory() as session:
        cats = list((await session.execute(select(TeamCategory).order_by(TeamCategory.id))).scalars())

    llm = get_llm()
    fam_vecs = await llm.embed([f"{f['module']} {f['name']}" for f in fam_list])
    cat_vecs = await llm.embed([f"{c.module} {c.category}" for c in cats])

    results = []
    for cat, cvec in zip(cats, cat_vecs, strict=True):
        # 같은 모듈 family 우선, 없으면 전체 — 이름 유사도 top-1
        ranked = sorted(
            (
                (_cosine(cvec, fvec) + (0.15 if f["module"] == cat.module else 0), f["family_id"], f["name"])
                for f, fvec in zip(fam_list, fam_vecs, strict=True)
            ),
            reverse=True,
        )
        top = ranked[0]
        results.append({
            "category": cat.category, "module": cat.module,
            "family_id": top[1], "family_name": top[2], "sim": round(top[0], 3),
            "alts": [(fid, nm, round(s, 3)) for s, fid, nm in ranked[1:3]],
        })
    return results


def render_yaml(results: list[dict]) -> str:
    lines = [
        f"{AUTO_GEN_MARKER} — 카테고리↔family 자동 매핑 (모듈 일치 + 이름 유사도).",
        "# 잘못된 매핑은 family_id 값을 직접 고치세요. 손편집하려면 첫 줄 마커를 지우세요.",
        "",
    ]
    for r in results:
        alt = ", ".join(f"{fid}({nm}) {s}" for fid, nm, s in r["alts"])
        lines.append(f"# {r['category']} [{r['module']}] → {r['family_name']} (sim {r['sim']}) | 차순위: {alt}")
        lines.append(f'"{r["category"]}": {r["family_id"]}')
    return "\n".join(lines) + "\n"


async def main(out_path: str | None = None) -> None:
    results = await build_mapping()
    out = Path(out_path) if out_path else (
        Path(settings.data_dir) / "prompts" / "npc" / "category_family_map.yaml"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_yaml(results), encoding="utf-8")
    low = [r for r in results if r["sim"] < 0.6]
    print(f"매핑 완료: 카테고리 {len(results)}개 → {out}")
    print(f"유사도 낮음(<0.6, 검수 우선): {len(low)}건")
    for r in low:
        print(f"  ⚠️ {r['category']} → {r['family_name']} (sim {r['sim']})")


if __name__ == "__main__":
    asyncio.run(main(sys.argv[1] if len(sys.argv) > 1 else None))
