"""추천 직무(KB) → 체험 시나리오 매핑 생성 — "적성 → 맞는 직무 체험" 연결 고리.

추천 직무 taxonomy(KB ~105개)와 게임 시나리오 직무(팀 조사 40개)는 출처가 달라
거의 겹치지 않는다(교집합 1개). 이 스크립트가 둘을 잇는다:

  1) 코드가 정확히 일치하면 그대로 (backend-developer 등)
  2) 아니면 임베딩 코사인 유사도로 가장 가까운 시나리오 top-1 선택
  3) 결과를 사람 검수용 YAML(data/recommendation/job_scenario_map.yaml)로 방출
     — 각 항목 위에 top-3 후보와 유사도를 주석으로 남겨 검수가 쉽게

이 YAML이 최종 소스다: 팀이 잘못된 매핑을 직접 고치면 그게 우선이고,
재생성 시 AUTO-GENERATED 마커가 없으면 덮어쓰지 않는다 (build_scenarios와 동일 규칙).

사용: docker compose exec api python -m app.scripts.map_jobs_to_scenarios [out_path]
      (컨테이너 data/는 읽기전용 — out_path로 방출 후 호스트 data/recommendation/에 복사)
"""

import asyncio
import logging
import math
import sys
from pathlib import Path

from sqlalchemy import select

from app.core.config import settings
from app.llm import get_llm
from app.models import Job, Scenario

logger = logging.getLogger(__name__)

AUTO_GEN_MARKER = "# AUTO-GENERATED by map_jobs_to_scenarios"
EMBED_BATCH = 32  # 프로바이더 배치 한도 보호


def cosine(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    return dot / (na * nb) if na and nb else 0.0


async def _embed_all(texts: list[str]) -> list[list[float]]:
    llm = get_llm()
    vectors: list[list[float]] = []
    for i in range(0, len(texts), EMBED_BATCH):
        vectors.extend(await llm.embed(texts[i : i + EMBED_BATCH]))
    return vectors


async def build_mapping() -> list[dict]:
    """→ [{job_code, job_title, slug, sim, alternatives: [(slug,title,sim)...]}] (job code순)."""
    from app.core.db import SessionFactory

    from app.domains.recommendation.service import is_recommendable

    async with SessionFactory() as session:
        # 추천 후보 자격과 동일 기준 — competencies 또는 dimension_weights (recommendation.is_recommendable).
        # dimension_weights만 있는 카테고리 직무(kts/ms/ys/jm/yg/stn/sns-*)도 추천에 뜨므로
        # 매핑에 포함해야 '체험' 연결이 끊기지 않는다. 이들은 code가 곧 시나리오 slug라 아래
        # `job.code in scen_codes` 분기에서 임베딩 없이 항등 매핑(sim 1.0)된다.
        jobs = [j for j in (await session.execute(select(Job))).scalars() if is_recommendable(j)]
        scen_rows = (
            await session.execute(select(Scenario, Job).join(Job, Scenario.job_id == Job.id))
        ).all()

    scen_meta = [(sc.slug, jb.title, f"{jb.title}. {(jb.description or '')[:400]}")
                 for sc, jb in scen_rows]
    scen_codes = {jb.code: sc.slug for sc, jb in scen_rows}

    scen_vecs = await _embed_all([t for _, _, t in scen_meta])
    job_vecs = await _embed_all(
        [f"{j.title}. {(j.description or '')[:400]}" for j in jobs]
    )

    results = []
    for job, jvec in zip(jobs, job_vecs):
        if job.code in scen_codes:  # 자기 시나리오가 있으면 그게 정답 (임베딩 불필요)
            results.append({
                "job_code": job.code, "job_title": job.title,
                "slug": scen_codes[job.code], "sim": 1.0, "alternatives": [],
            })
            continue
        ranked = sorted(
            ((cosine(jvec, svec), slug, title) for (slug, title, _), svec in zip(scen_meta, scen_vecs)),
            reverse=True,
        )
        top = ranked[0]
        results.append({
            "job_code": job.code, "job_title": job.title,
            "slug": top[1], "sim": top[0],
            "alternatives": [(s, t, round(sim, 3)) for sim, s, t in ranked[1:3]],
        })
    results.sort(key=lambda r: r["job_code"])
    return results


def render_yaml(results: list[dict]) -> str:
    """검수하기 좋은 YAML — 항목마다 매핑 근거(제목·유사도·차순위)를 주석으로."""
    lines = [
        f"{AUTO_GEN_MARKER} — 임베딩 유사도 top-1 자동 매핑.",
        "# 이 파일이 최종 소스: 잘못된 매핑은 값을 직접 고치세요 (없앨 직무는 값을 null로).",
        "# 손으로 편집하려면 첫 줄 마커를 지우세요 — 재생성이 이 파일을 보호합니다.",
        "",
    ]
    for r in results:
        alt = ", ".join(f"{s}({t}) {sim}" for s, t, sim in r["alternatives"])
        lines.append(f"# {r['job_title']} → sim {round(r['sim'], 3)}" + (f" | 차순위: {alt}" if alt else ""))
        lines.append(f"{r['job_code']}: {r['slug']}")
    return "\n".join(lines) + "\n"


async def main(out_path: str | None = None) -> None:
    results = await build_mapping()
    body = render_yaml(results)

    out = Path(out_path) if out_path else (
        Path(settings.data_dir) / "recommendation" / "job_scenario_map.yaml"
    )
    check = Path(settings.data_dir) / "recommendation" / "job_scenario_map.yaml"
    if check.exists() and AUTO_GEN_MARKER not in check.read_text(encoding="utf-8"):
        print(f"보호: {check} 는 손편집본 — 방출하지 않음. (재생성하려면 마커 줄을 복원하세요)")
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")

    low = [r for r in results if r["sim"] < 0.55]
    print(f"매핑 완료: 직무 {len(results)}건 → {out}")
    print(f"유사도 0.55 미만 (검수 우선순위): {len(low)}건")
    for r in low[:10]:
        print(f"  ⚠️ {r['job_code']} {r['job_title']} → {r['slug']} (sim {round(r['sim'], 3)})")


if __name__ == "__main__":
    asyncio.run(main(sys.argv[1] if len(sys.argv) > 1 else None))
