"""reports consultation_id, nullable simulation_id

Revision ID: 16dcc6e97d3d
Revises: 95fa0d143d6f
Create Date: 2026-07-09 05:42:10.626688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '16dcc6e97d3d'
down_revision: Union[str, None] = '95fa0d143d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('consultation_id', sa.Integer(), nullable=True))
    op.alter_column('reports', 'simulation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'reports', 'consultations', ['consultation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'simulation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reports', 'consultation_id')
    # ### end Alembic commands ###
