"""consultation survey column

Revision ID: 1a844a4f6a32
Revises: cd66ef9611a7
Create Date: 2026-07-13 06:17:45.224861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '1a844a4f6a32'
down_revision: Union[str, None] = 'cd66ef9611a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('survey', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'survey')
    # ### end Alembic commands ###
