"""doc_chunks job_code, file_hash

Revision ID: 95fa0d143d6f
Revises: 076c2c65b11f
Create Date: 2026-07-09 05:35:26.366903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '95fa0d143d6f'
down_revision: Union[str, None] = '076c2c65b11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_chunks', sa.Column('job_code', sa.String(length=50), nullable=True))
    op.add_column('doc_chunks', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_doc_chunks_job_code'), 'doc_chunks', ['job_code'], unique=False)
    op.create_index(op.f('ix_doc_chunks_source'), 'doc_chunks', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_chunks_source'), table_name='doc_chunks')
    op.drop_index(op.f('ix_doc_chunks_job_code'), table_name='doc_chunks')
    op.drop_column('doc_chunks', 'file_hash')
    op.drop_column('doc_chunks', 'job_code')
    # ### end Alembic commands ###
