"""research source tables

Revision ID: b3aacc38133f
Revises: 759335bb9342
Create Date: 2026-07-12 12:43:55.519468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'b3aacc38133f'
down_revision: Union[str, None] = '759335bb9342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_code', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=30), nullable=True),
    sa.Column('section', sa.String(length=30), nullable=True),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('stage_goal', sa.Text(), nullable=True),
    sa.Column('npc_roles', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('failure_patterns', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_code')
    )
    op.create_table('kb_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_code', sa.String(length=10), nullable=False),
    sa.Column('family_id', sa.String(length=10), nullable=False),
    sa.Column('job_group', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=True),
    sa.Column('in_use', sa.String(length=5), nullable=True),
    sa.Column('entry_level', sa.String(length=30), nullable=True),
    sa.Column('interest_type', sa.String(length=30), nullable=True),
    sa.Column('work_targets', sa.Text(), nullable=True),
    sa.Column('npc_roles', sa.Text(), nullable=True),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('first_scenario', sa.Text(), nullable=True),
    sa.Column('process_flow', sa.Text(), nullable=True),
    sa.Column('main_mission', sa.Text(), nullable=True),
    sa.Column('mission_steps', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('failure_patterns', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_code')
    )
    op.create_index(op.f('ix_kb_jobs_family_id'), 'kb_jobs', ['family_id'], unique=False)
    op.create_index(op.f('ix_kb_jobs_module'), 'kb_jobs', ['module'], unique=False)
    op.create_table('kb_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_code', sa.String(length=15), nullable=False),
    sa.Column('job_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('family_id', sa.String(length=10), nullable=True),
    sa.Column('job_group', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=30), nullable=True),
    sa.Column('stage_id', sa.String(length=5), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('stage_goal', sa.Text(), nullable=True),
    sa.Column('work_targets', sa.Text(), nullable=True),
    sa.Column('npc_roles', sa.Text(), nullable=True),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('mission_candidate', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('failure_patterns', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_code'),
    sa.UniqueConstraint('job_code', 'stage_id')
    )
    op.create_index(op.f('ix_kb_stages_job_code'), 'kb_stages', ['job_code'], unique=False)
    op.create_table('team_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('ledger_rows', sa.String(length=20), nullable=True),
    sa.Column('ledger_job_kinds', sa.String(length=20), nullable=True),
    sa.Column('rag_status', sa.String(length=10), nullable=True),
    sa.Column('rag_family', sa.String(length=100), nullable=True),
    sa.Column('rag_job_count', sa.String(length=10), nullable=True),
    sa.Column('rag_job_ids', sa.String(length=100), nullable=True),
    sa.Column('rag_jobs', sa.Text(), nullable=True),
    sa.Column('work_flow', sa.Text(), nullable=True),
    sa.Column('npc_roles', sa.Text(), nullable=True),
    sa.Column('inputs', sa.Text(), nullable=True),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('mission_candidates', sa.Text(), nullable=True),
    sa.Column('sudden_events', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_index(op.f('ix_team_categories_module'), 'team_categories', ['module'], unique=False)
    op.create_table('team_job_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('assigned_jobs', sa.Text(), nullable=True),
    sa.Column('ledger_jobs', sa.Text(), nullable=True),
    sa.Column('standard_tasks', sa.Text(), nullable=True),
    sa.Column('core_competencies', sa.Text(), nullable=True),
    sa.Column('evidence_files', sa.Text(), nullable=True),
    sa.Column('review_memo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('team_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=True),
    sa.Column('mission_code', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('situation_type', sa.String(length=30), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('npc', sa.Text(), nullable=True),
    sa.Column('npc_line', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('action_steps', sa.Text(), nullable=True),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('failure_patterns', sa.Text(), nullable=True),
    sa.Column('extra_event', sa.Text(), nullable=True),
    sa.Column('rag_link', sa.String(length=100), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('impl_form', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_code')
    )
    op.create_index(op.f('ix_team_missions_category'), 'team_missions', ['category'], unique=False)
    op.create_index(op.f('ix_team_missions_module'), 'team_missions', ['module'], unique=False)
    op.create_table('team_rep_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('mission_code', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('npc', sa.Text(), nullable=True),
    sa.Column('core_mission', sa.Text(), nullable=True),
    sa.Column('user_actions', sa.Text(), nullable=True),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('eval_focus', sa.Text(), nullable=True),
    sa.Column('rag_status', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_code')
    )
    op.create_index(op.f('ix_team_rep_missions_category'), 'team_rep_missions', ['category'], unique=False)
    op.create_table('team_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=True),
    sa.Column('stage_id', sa.String(length=5), nullable=False),
    sa.Column('stage_name', sa.String(length=100), nullable=True),
    sa.Column('stage_goal', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('npc_roles', sa.Text(), nullable=True),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('mission_candidate', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('failure_patterns', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'stage_id')
    )
    op.create_index(op.f('ix_team_stages_category'), 'team_stages', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # kb_stages와 짝을 이루는 kb-v5 임베딩 청크도 함께 정리 (원본 없는 고아 RAG 청크 방지)
    op.execute("DELETE FROM doc_chunks WHERE source LIKE 'kb-v5/%'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_stages_category'), table_name='team_stages')
    op.drop_table('team_stages')
    op.drop_index(op.f('ix_team_rep_missions_category'), table_name='team_rep_missions')
    op.drop_table('team_rep_missions')
    op.drop_index(op.f('ix_team_missions_module'), table_name='team_missions')
    op.drop_index(op.f('ix_team_missions_category'), table_name='team_missions')
    op.drop_table('team_missions')
    op.drop_table('team_job_evidence')
    op.drop_index(op.f('ix_team_categories_module'), table_name='team_categories')
    op.drop_table('team_categories')
    op.drop_index(op.f('ix_kb_stages_job_code'), table_name='kb_stages')
    op.drop_table('kb_stages')
    op.drop_index(op.f('ix_kb_jobs_module'), table_name='kb_jobs')
    op.drop_index(op.f('ix_kb_jobs_family_id'), table_name='kb_jobs')
    op.drop_table('kb_jobs')
    op.drop_table('common_processes')
    # ### end Alembic commands ###
