"""scenario module and sudden_quest

Revision ID: cd66ef9611a7
Revises: b3aacc38133f
Create Date: 2026-07-13 01:28:33.017973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'cd66ef9611a7'
down_revision: Union[str, None] = 'b3aacc38133f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('module', sa.String(length=30), nullable=True))
    op.add_column('scenarios', sa.Column('sudden_quest', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_scenarios_module'), 'scenarios', ['module'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_module'), table_name='scenarios')
    op.drop_column('scenarios', 'sudden_quest')
    op.drop_column('scenarios', 'module')
    # ### end Alembic commands ###
